import type { Feedback } from "@/lib/types";

function SectionHeading({ title }: { title: string }) {
  return (
    <div>
      <h3 className="font-display text-[21px] font-semibold text-ink">{title}</h3>
      <div className="mt-1 h-px w-9 bg-gold" />
    </div>
  );
}

function Marker({ tone, glyph }: { tone: "pine" | "amber"; glyph: string }) {
  const cls =
    tone === "pine" ? "bg-pine-soft text-pine" : "bg-amber-soft text-amber";
  return (
    <span
      aria-hidden
      className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[11px] font-bold ${cls}`}
    >
      {glyph}
    </span>
  );
}

export function FeedbackReport({
  feedback,
  candidateName,
  candidateRole,
  sessionId,
}: {
  feedback: Feedback;
  candidateName?: string;
  candidateRole?: string;
  sessionId?: string | null;
}) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const stagger = (i: number) => ({ animationDelay: `${0.08 + i * 0.09}s` });

  return (
    <section
      data-testid="feedback-report"
      className="w-full animate-rise overflow-hidden rounded-3xl border border-line-strong bg-card shadow-[0_28px_70px_-34px_rgba(34,32,26,0.45)]"
    >
      <header className="border-b border-line bg-parchment/60 px-7 py-6 sm:px-9">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <span className="font-mono text-[10.5px] uppercase tracking-[0.24em] text-gold">
            Interview report
          </span>
          <span className="font-mono text-[11px] text-ink-faint">{date}</span>
        </div>
        <h2 className="mt-2.5 font-display text-[30px] font-semibold leading-tight tracking-tight text-ink">
          {candidateName ?? "Candidate"}
        </h2>
        <p className="mt-0.5 text-[13.5px] text-ink-soft">
          {[candidateRole, "EternityX 31-Day AI Cohort"].filter(Boolean).join(" · ")}
        </p>
      </header>

      <div className="animate-rise px-7 py-6 sm:px-9" style={stagger(0)}>
        <p className="text-[15.5px] leading-[1.75] text-ink first-letter:float-left first-letter:mr-2.5 first-letter:font-display first-letter:text-[46px] first-letter:font-semibold first-letter:leading-[0.82] first-letter:text-pine">
          {feedback.summary}
        </p>
      </div>

      <div className="grid gap-8 px-7 pb-7 sm:px-9 md:grid-cols-2">
        <div className="animate-rise" style={stagger(1)}>
          <SectionHeading title="Strengths" />
          <ul className="mt-4 space-y-3">
            {feedback.strengths.map((item) => (
              <li key={item} className="flex gap-3 text-[14px] leading-relaxed text-ink-soft">
                <Marker tone="pine" glyph="&#10003;" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="animate-rise" style={stagger(2)}>
          <SectionHeading title="Gaps" />
          <ul className="mt-4 space-y-3">
            {feedback.gaps.map((item) => (
              <li key={item} className="flex gap-3 text-[14px] leading-relaxed text-ink-soft">
                <Marker tone="amber" glyph="!" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="animate-rise px-7 pb-8 sm:px-9" style={stagger(3)}>
        <SectionHeading title="Recommended next steps" />
        <ol className="mt-4 space-y-3.5">
          {feedback.next.map((item, i) => (
            <li key={item} className="flex items-baseline gap-4">
              <span className="font-display text-[19px] font-semibold tabular-nums text-gold">
                {String(i + 1).padStart(2, "0")}
              </span>
              <span className="text-[14px] leading-relaxed text-ink-soft">{item}</span>
            </li>
          ))}
        </ol>
      </div>

      <footer className="flex flex-wrap items-center justify-between gap-2 border-t border-line bg-parchment/50 px-7 py-3 sm:px-9">
        <span className="font-mono text-[10.5px] uppercase tracking-[0.18em] text-ink-faint">
          Generated by the EternityX Interview Agent
        </span>
        {sessionId && (
          <span className="font-mono text-[10.5px] text-ink-faint">{sessionId}</span>
        )}
      </footer>
    </section>
  );
}
